aws_region = "us-east-1"
replica_region = "us-west-2"
bucket_name = "simple-storage-service-prod-final-us-east-1"
replica_bucket_name = "simple-storage-service-prod-final-us-west-2"
lambda_function_name = "simple-storage-service-processor-prod-final"
kms_key_alias = "alias/simple-storage-service-prod-final-kms"